project:
  type: website
  output-dir: "docs"
  
language: 
  search-text-placeholder: Search

website:
  title: "Ayorinde Ayomide David"
  
  favicon: favicon.png
  
  search: 
    type: textbox
  
  site-url: https://ayo-ayorinde.github.io
  
  announcement: 
    icon: bell
    dismissable: true
    content: >
      **Announcement** – Welcome to my portfolio website, a curated space highlighting my academic journey, research endeavors, and analytical projects. Feel free to explore, connect, and engage with my work. 
    position: below-navbar
    type: light
  
  navbar:
      collapse: false
      logo: favicon.png
      left: 
        - text: "Home"
          file: index.qmd
        - text: "Portfolio" 
          file: portfolio.qmd
        - text: "CV"
          file: cv.qmd
      right:
      - icon: linkedin
        href: https://www.linkedin.com/in/ayorindeayomide/
      - icon: twitter
        href: https://x.com/Data_General1
      - icon: github
        href: https://github.com/Ayo-Ayorinde
  page-footer: 
    center: "© 2025 Ayomide Ayorinde • Powered by Quarto & GitHub Pages"

format:
  html:
    theme: united
    css: styles.css



