project:
  type: website
  output-dir: "docs"

website:
  title: "Ayorinde Ayomide David"
  navbar:
      left: 
        - text: "Home"
          file: index.qmd
        - text: "Portfolio" 
          file: portfolio.qmd
        - text: "CV"
          file: cv.qmd
      right:
      - icon: linkedin
        href: https://www.linkedin.com/in/ayorindeayomide/
      - icon: twitter
        href: https://twitter.com
      - icon: github
        href: https://github.com/Aysquare
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



