<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ayorinde Ayomide David">
<meta name="dcterms.date" content="2025-08-11">

<title>A Cross-Sectional Study of the Effect of Age, College and Sex on Academic Performance among FUNAAB Graduates Mobilized for NYSC in 2024 – Ayorinde Ayomide David</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-de84f8d6bb715db06a919283c2d1e787.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-64a2ce9411aa0d9224ef009a42f913f5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "Search",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../favicon.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Ayorinde Ayomide David</span>
    </a>
  </div>
          <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../portfolio.html"> 
<span class="menu-text">Portfolio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../cv.html"> 
<span class="menu-text">CV</span></a>
  </li>  
</ul>
          <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/ayorindeayomide/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://x.com/Data_General1"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Ayo-Ayorinde"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          <div class="quarto-navbar-tools">
</div>
            <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <div id="quarto-announcement" data-announcement-id="6e2e9eb7100d489eacb5fd038d0d7381" class="alert alert-light hidden"><i class="bi bi-bell quarto-announcement-icon"></i><div class="quarto-announcement-content">
<p><strong>Announcement</strong> – Welcome to my portfolio website, a curated space highlighting my academic journey, research endeavors, and analytical projects. Feel free to explore, connect, and engage with my work.</p>
</div><i class="bi bi-x-lg quarto-announcement-action"></i></div>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#objective-of-the-study" id="toc-objective-of-the-study" class="nav-link" data-scroll-target="#objective-of-the-study">Objective of the Study</a></li>
  <li><a href="#data-description" id="toc-data-description" class="nav-link" data-scroll-target="#data-description">Data Description</a></li>
  <li><a href="#data-exploration-cleaning-manipulation-and-transformation" id="toc-data-exploration-cleaning-manipulation-and-transformation" class="nav-link" data-scroll-target="#data-exploration-cleaning-manipulation-and-transformation">Data Exploration, Cleaning, Manipulation and Transformation</a>
  <ul>
  <li><a href="#data-exploration" id="toc-data-exploration" class="nav-link" data-scroll-target="#data-exploration">Data Exploration</a></li>
  <li><a href="#data-cleaning" id="toc-data-cleaning" class="nav-link" data-scroll-target="#data-cleaning">Data Cleaning</a></li>
  <li><a href="#data-manipulation-and-transformation" id="toc-data-manipulation-and-transformation" class="nav-link" data-scroll-target="#data-manipulation-and-transformation">Data Manipulation and Transformation</a></li>
  </ul></li>
  <li><a href="#data-analysis-and-visualization" id="toc-data-analysis-and-visualization" class="nav-link" data-scroll-target="#data-analysis-and-visualization">Data Analysis and Visualization</a>
  <ul>
  <li><a href="#gender-as-a-predictor-of-academic-achievement" id="toc-gender-as-a-predictor-of-academic-achievement" class="nav-link" data-scroll-target="#gender-as-a-predictor-of-academic-achievement">Gender as a Predictor of Academic Achievement</a>
  <ul class="collapse">
  <li><a href="#chi-square-test-of-independence" id="toc-chi-square-test-of-independence" class="nav-link" data-scroll-target="#chi-square-test-of-independence">Chi-Square Test of Independence</a></li>
  </ul></li>
  <li><a href="#college-as-a-predictor-of-academic-achievement" id="toc-college-as-a-predictor-of-academic-achievement" class="nav-link" data-scroll-target="#college-as-a-predictor-of-academic-achievement">College as a Predictor of Academic Achievement</a>
  <ul class="collapse">
  <li><a href="#chi-square-test-of-independence-1" id="toc-chi-square-test-of-independence-1" class="nav-link" data-scroll-target="#chi-square-test-of-independence-1">Chi-Square Test of independence</a></li>
  <li><a href="#post-hoc-test" id="toc-post-hoc-test" class="nav-link" data-scroll-target="#post-hoc-test">Post-Hoc Test</a></li>
  </ul></li>
  <li><a href="#combined-effect-of-age-gender-college-affiliation-on-the-class-of-degree-attained" id="toc-combined-effect-of-age-gender-college-affiliation-on-the-class-of-degree-attained" class="nav-link" data-scroll-target="#combined-effect-of-age-gender-college-affiliation-on-the-class-of-degree-attained">Combined Effect of Age, Gender, College Affiliation on the Class of Degree Attained</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">A Cross-Sectional Study of the Effect of Age, College and Sex on Academic Performance among FUNAAB Graduates Mobilized for NYSC in 2024</h1>
  <div class="quarto-categories">
    <div class="quarto-category">code</div>
    <div class="quarto-category">analysis</div>
    <div class="quarto-category">r</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ayorinde Ayomide David </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2025-08-11</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Academic performance remains a central concern for educators, policymakers, and researchers, especially in higher education institutions where various individual and institutional factors may shape students’ academic outcomes. While curriculum content and instructional methods often receive primary attention, growing evidence suggests that demographic characteristics—such as age, gender, academic discipline, and region of origin may significantly influence students’ academic achievements.</p>
<p>Age has been associated with varying levels of academic maturity, motivation, and learning capacity. Younger students may possess cognitive flexibility but lack the life experience that older students bring to their studies. Similarly, gender disparities in academic performance, often shaped by socio-cultural expectations and opportunities, continue to attract scholarly interest. In Nigeria and beyond, gender-based performance gaps have been observed across academic disciplines, with conflicting findings on whether male or female students outperform their counterparts.</p>
<p>Additionally, the academic department or field of study introduces another layer of complexity. Differences in academic rigor, grading policies, and student support structures across departments may contribute to observable disparities in academic outcomes. However, using department as a predictor can be statistically problematic due to sample size imbalances and high variability. As such, grouping departments into broader academic units such as colleges offers a more stable and interpretable approach to understanding institutional influences on performance.</p>
<p>This study aims to examine the influence of age, gender, and college affiliation on the academic performance of graduates from the Federal University of Agriculture, Abeokuta (FUNAAB), using data from the 2023/2024 NYSC mobilization list. Academic performance is operationalized using the class of degree attained, which serves as a reliable proxy in the absence of raw CGPA. By focusing on a single graduating cohort, the study offers a cross-sectional snapshot of demographic and institutional patterns that may underlie academic success. The findings will provide insights into potential equity issues and inform academic support strategies within the university setting.</p>
</section>
<section id="objective-of-the-study" class="level2">
<h2 class="anchored" data-anchor-id="objective-of-the-study">Objective of the Study</h2>
<p>The primary objective of this study is to examine the effect of age, gender, college affiliation, and region of origin on the academic performance of graduates from the Federal University of Agriculture, Abeokuta, using the 2023/2024 NYSC mobilization list.</p>
<p>Specifically, the study seeks to:</p>
<ul>
<li><p>Assess the relationship between gender and academic performance among the graduates.</p></li>
<li><p>Evaluate the extent to which college affiliation (as a proxy for department) affects academic outcomes.</p></li>
<li><p>Explore the combined effect of age, gender, college affiliation, and region on the class of degree attained.</p></li>
</ul>
</section>
<section id="data-description" class="level2">
<h2 class="anchored" data-anchor-id="data-description">Data Description</h2>
<p>This dataset used in this study was obtained from the 2023/24 National Youth Service Corps (NYSC) mobilization list of the Federal University of Agriculture, Abeokuta (FUNAAB). This dataset comprises information on 3406 graduates who were successfully mobilized for national service.</p>
<p>The dataset includes demographic, academic, and institutional variables relevant to the analysis of academic performance. Each row in the dataset represents an individual graduate, and the variables collected include:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gt</span>(<span class="fu">data.frame</span>(<span class="at">Variable_Name =</span> <span class="fu">c</span>(<span class="st">"matriculation_no"</span>, <span class="st">"state"</span>, <span class="st">"courseof_study"</span>, <span class="st">"class_of_grade"</span>, <span class="st">"marital_status"</span>,<span class="st">"gender"</span>, <span class="st">"date_of_birth"</span>, <span class="st">"college"</span>, <span class="st">"department_code"</span>, <span class="st">"age"</span>, <span class="st">"region"</span>), <span class="at">Description =</span> <span class="fu">c</span>(<span class="st">"A unique identifier for each student"</span>, <span class="st">"The Nigeria state attributed to the graduate"</span>, <span class="st">"The degree programme pursued by the graduate"</span>,<span class="st">"The final class of degree awarded to the student"</span>, <span class="st">"The marital status of the graduate (Married or Single)"</span>,<span class="st">"The sex of the graduate (Male or Female)"</span>,<span class="st">"The graduate date of birth"</span>, <span class="st">"The academic unit or faculty under which the student graduated"</span>, <span class="st">"Abbreviated code representing the graduate's department"</span>, <span class="st">"Age of graduate"</span>, <span class="st">"The Nigeria region attributed to the graduate"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="bdduixzlon" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#bdduixzlon table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#bdduixzlon thead, #bdduixzlon tbody, #bdduixzlon tfoot, #bdduixzlon tr, #bdduixzlon td, #bdduixzlon th {
  border-style: none;
}

#bdduixzlon p {
  margin: 0;
  padding: 0;
}

#bdduixzlon .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#bdduixzlon .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#bdduixzlon .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#bdduixzlon .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#bdduixzlon .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#bdduixzlon .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#bdduixzlon .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#bdduixzlon .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#bdduixzlon .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#bdduixzlon .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#bdduixzlon .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#bdduixzlon .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#bdduixzlon .gt_spanner_row {
  border-bottom-style: hidden;
}

#bdduixzlon .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#bdduixzlon .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#bdduixzlon .gt_from_md > :first-child {
  margin-top: 0;
}

#bdduixzlon .gt_from_md > :last-child {
  margin-bottom: 0;
}

#bdduixzlon .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#bdduixzlon .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#bdduixzlon .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#bdduixzlon .gt_row_group_first td {
  border-top-width: 2px;
}

#bdduixzlon .gt_row_group_first th {
  border-top-width: 2px;
}

#bdduixzlon .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#bdduixzlon .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#bdduixzlon .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#bdduixzlon .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#bdduixzlon .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#bdduixzlon .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#bdduixzlon .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#bdduixzlon .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#bdduixzlon .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#bdduixzlon .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#bdduixzlon .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#bdduixzlon .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#bdduixzlon .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#bdduixzlon .gt_left {
  text-align: left;
}

#bdduixzlon .gt_center {
  text-align: center;
}

#bdduixzlon .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#bdduixzlon .gt_font_normal {
  font-weight: normal;
}

#bdduixzlon .gt_font_bold {
  font-weight: bold;
}

#bdduixzlon .gt_font_italic {
  font-style: italic;
}

#bdduixzlon .gt_super {
  font-size: 65%;
}

#bdduixzlon .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#bdduixzlon .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#bdduixzlon .gt_indent_1 {
  text-indent: 5px;
}

#bdduixzlon .gt_indent_2 {
  text-indent: 10px;
}

#bdduixzlon .gt_indent_3 {
  text-indent: 15px;
}

#bdduixzlon .gt_indent_4 {
  text-indent: 20px;
}

#bdduixzlon .gt_indent_5 {
  text-indent: 25px;
}

#bdduixzlon .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#bdduixzlon div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="gt_col_headings header">
<th id="Variable_Name" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Variable_Name</th>
<th id="Description" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Description</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="Variable_Name">matriculation_no</td>
<td class="gt_row gt_left" headers="Description">A unique identifier for each student</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable_Name">state</td>
<td class="gt_row gt_left" headers="Description">The Nigeria state attributed to the graduate</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable_Name">courseof_study</td>
<td class="gt_row gt_left" headers="Description">The degree programme pursued by the graduate</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable_Name">class_of_grade</td>
<td class="gt_row gt_left" headers="Description">The final class of degree awarded to the student</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable_Name">marital_status</td>
<td class="gt_row gt_left" headers="Description">The marital status of the graduate (Married or Single)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable_Name">gender</td>
<td class="gt_row gt_left" headers="Description">The sex of the graduate (Male or Female)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable_Name">date_of_birth</td>
<td class="gt_row gt_left" headers="Description">The graduate date of birth</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable_Name">college</td>
<td class="gt_row gt_left" headers="Description">The academic unit or faculty under which the student graduated</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable_Name">department_code</td>
<td class="gt_row gt_left" headers="Description">Abbreviated code representing the graduate's department</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable_Name">age</td>
<td class="gt_row gt_left" headers="Description">Age of graduate</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable_Name">region</td>
<td class="gt_row gt_left" headers="Description">The Nigeria region attributed to the graduate</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="data-exploration-cleaning-manipulation-and-transformation" class="level2">
<h2 class="anchored" data-anchor-id="data-exploration-cleaning-manipulation-and-transformation">Data Exploration, Cleaning, Manipulation and Transformation</h2>
<p>To begin the analysis, the necessary R packages were loaded, including tidyverse, gt, here, janitor, lubridate, and visdat, which collectively support data manipulation, visualization, and cleaning. Following this, the NYSC dataset was imported into the R environment. An initial assessment was conducted to determine the dataset’s structure, including the number of rows and columns, and to preview the first ten records.</p>
<p>The properties of each variable were inspected to understand data types and formats. Special attention was given to the Date of Graduation column, which was found to contain a substantial number of missing values. This observation was first noted during the structure inspection and subsequently confirmed using summary statistics and missing value checks.</p>
<p>To preserve confidentiality and ensure ethical data handling, columns containing sensitive or personally identifiable information such as names, phone numbers,jamb registration number and matric numbers were excluded from the working dataset. A new CSV file was then generated to store this modified version of the dataset.</p>
<p>Finally, data cleaning and transformation were carried out on the refined dataset. This included tasks such as deriving new variables (age and region), and preparing the data for statistical analysis.</p>
<section id="data-exploration" class="level3">
<h3 class="anchored" data-anchor-id="data-exploration">Data Exploration</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#nysc &lt;- read_csv(here("Data/NYSC.csv"))    # Loading the dataset into R</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co">#dim(nysc) # Investigating the dimension of the dataset</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co">#head(nysc, n= 10) # Exploring the first 10 rows of the dataset</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co">#glimpse(nysc)    # Inspecting the dataset</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co">#sum(is.na(nysc$`Date of Graduation`))    # Investigating the number of missing values in the Date of Graduation colunm</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co">#nysc_list &lt;- nysc %&gt;% # Dropping private information columns and the column with no entry</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="co">#mutate(id = str_sub(JambNumber, -8, -1)) %&gt;% </span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  <span class="co">#select(-c(Firstname,Middlename, Surname, MatriculationNo,JambNumber, Phone, `Date of Graduation`)) %&gt;% </span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>  <span class="co">#select(id, everything())</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="co">#write_csv(nysc_list,"nysc_modified.csv") # Creating a csv file for the modified dataset</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="data-cleaning" class="level3">
<h3 class="anchored" data-anchor-id="data-cleaning">Data Cleaning</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>nysc_list_modified <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"posts/Academic performance/data/nysc_modified.csv"</span>)) <span class="co"># Loading the modified dataset into R</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">vis_dat</span>(nysc_list_modified) <span class="co"># Visualizing the dataset to investigate it's properties</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>nysc_list_modified_cleaned <span class="ot">&lt;-</span> nysc_list_modified <span class="sc">%&gt;%</span>    <span class="co"># Cleaning the column name for consistency</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">clean_names</span>()</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>nysc_list_modified_cleaned <span class="sc">%&gt;%</span>  <span class="co"># Identifying duplicated rows based on matriculation number</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_dupes</span>(id)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,942 × 10
   id       dupe_count statename  courseof_study   class_of_grade marital_status
   &lt;chr&gt;         &lt;int&gt; &lt;chr&gt;      &lt;chr&gt;            &lt;chr&gt;          &lt;chr&gt;         
 1 000108IC          2 Ogun State AGRICULTURE/B.A… Second Class … S             
 2 000108IC          2 Ogun State AGRICULTURE/B.A… Second Class … S             
 3 001054FH          2 Ogun State AQUACULTURE AND… Second Class … S             
 4 001054FH          2 Ogun State AQUACULTURE AND… Second Class … S             
 5 001145HF          2 Ogun State AGRICULTURE/B.A… Second Class … S             
 6 001145HF          2 Ogun State AGRICULTURE/B.A… Second Class … S             
 7 003265CA          2 Ondo State AGRICULTURE/B.A… Second Class … S             
 8 003265CA          2 Ondo State AGRICULTURE/B.A… Second Class … S             
 9 003289EF          2 Ogun State AGRICULTURE/B.A… Second Class … S             
10 003289EF          2 Ogun State AGRICULTURE/B.A… Second Class … S             
# ℹ 1,932 more rows
# ℹ 4 more variables: gender &lt;chr&gt;, date_of_birth &lt;date&gt;, college &lt;chr&gt;,
#   deptment_code &lt;chr&gt;</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>nysc_list_modified_cleaned <span class="ot">&lt;-</span> nysc_list_modified_cleaned <span class="sc">%&gt;%</span>    <span class="co"># Dropping duplicated rows</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unique</span>()</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>nysc_list_modified_cleaned <span class="ot">&lt;-</span> nysc_list_modified_cleaned <span class="sc">%&gt;%</span> </span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">class_of_grade =</span> <span class="fu">factor</span>(class_of_grade,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Third Class"</span>,<span class="st">"Second Class Lower"</span>, <span class="st">"Second Class Upper"</span>, <span class="st">"First Class"</span>), </span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">ordered =</span> T),</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">gender =</span> <span class="fu">factor</span>(gender),</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">college =</span> <span class="fu">factor</span>(college))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="data-manipulation-and-transformation" class="level3">
<h3 class="anchored" data-anchor-id="data-manipulation-and-transformation">Data Manipulation and Transformation</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>nysc_list_modified_cleaned <span class="sc">%&gt;%</span> <span class="co"># Inspecting the entries of each column excluding jamb_number</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>id) <span class="sc">%&gt;%</span> </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tbl_summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="rpcfroqubq" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#rpcfroqubq table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#rpcfroqubq thead, #rpcfroqubq tbody, #rpcfroqubq tfoot, #rpcfroqubq tr, #rpcfroqubq td, #rpcfroqubq th {
  border-style: none;
}

#rpcfroqubq p {
  margin: 0;
  padding: 0;
}

#rpcfroqubq .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#rpcfroqubq .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#rpcfroqubq .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#rpcfroqubq .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#rpcfroqubq .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#rpcfroqubq .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#rpcfroqubq .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#rpcfroqubq .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#rpcfroqubq .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#rpcfroqubq .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#rpcfroqubq .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#rpcfroqubq .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#rpcfroqubq .gt_spanner_row {
  border-bottom-style: hidden;
}

#rpcfroqubq .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#rpcfroqubq .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#rpcfroqubq .gt_from_md > :first-child {
  margin-top: 0;
}

#rpcfroqubq .gt_from_md > :last-child {
  margin-bottom: 0;
}

#rpcfroqubq .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#rpcfroqubq .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#rpcfroqubq .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#rpcfroqubq .gt_row_group_first td {
  border-top-width: 2px;
}

#rpcfroqubq .gt_row_group_first th {
  border-top-width: 2px;
}

#rpcfroqubq .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#rpcfroqubq .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#rpcfroqubq .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#rpcfroqubq .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#rpcfroqubq .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#rpcfroqubq .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#rpcfroqubq .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#rpcfroqubq .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#rpcfroqubq .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#rpcfroqubq .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#rpcfroqubq .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#rpcfroqubq .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#rpcfroqubq .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#rpcfroqubq .gt_left {
  text-align: left;
}

#rpcfroqubq .gt_center {
  text-align: center;
}

#rpcfroqubq .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#rpcfroqubq .gt_font_normal {
  font-weight: normal;
}

#rpcfroqubq .gt_font_bold {
  font-weight: bold;
}

#rpcfroqubq .gt_font_italic {
  font-style: italic;
}

#rpcfroqubq .gt_super {
  font-size: 65%;
}

#rpcfroqubq .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#rpcfroqubq .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#rpcfroqubq .gt_indent_1 {
  text-indent: 5px;
}

#rpcfroqubq .gt_indent_2 {
  text-indent: 10px;
}

#rpcfroqubq .gt_indent_3 {
  text-indent: 15px;
}

#rpcfroqubq .gt_indent_4 {
  text-indent: 20px;
}

#rpcfroqubq .gt_indent_5 {
  text-indent: 25px;
}

#rpcfroqubq .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#rpcfroqubq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="gt_col_headings header">
<th id="label" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"><strong>Characteristic</strong></th>
<th id="stat_0" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>N = 3,406</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="label">statename</td>
<td class="gt_row gt_center" headers="stat_0"><br>
</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Abia State</td>
<td class="gt_row gt_center" headers="stat_0">1 (&lt;0.1%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Akwa Ibom State</td>
<td class="gt_row gt_center" headers="stat_0">3 (&lt;0.1%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Anambra State</td>
<td class="gt_row gt_center" headers="stat_0">2 (&lt;0.1%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Benue State</td>
<td class="gt_row gt_center" headers="stat_0">4 (0.1%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Cross River State</td>
<td class="gt_row gt_center" headers="stat_0">2 (&lt;0.1%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Delta State</td>
<td class="gt_row gt_center" headers="stat_0">19 (0.6%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Ebonyi State</td>
<td class="gt_row gt_center" headers="stat_0">1 (&lt;0.1%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Edo State</td>
<td class="gt_row gt_center" headers="stat_0">13 (0.4%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Ekiti State</td>
<td class="gt_row gt_center" headers="stat_0">38 (1.1%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Enugu State</td>
<td class="gt_row gt_center" headers="stat_0">3 (&lt;0.1%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;FCT</td>
<td class="gt_row gt_center" headers="stat_0">6 (0.2%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Imo State</td>
<td class="gt_row gt_center" headers="stat_0">7 (0.2%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Kaduna State</td>
<td class="gt_row gt_center" headers="stat_0">2 (&lt;0.1%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Kogi State</td>
<td class="gt_row gt_center" headers="stat_0">12 (0.4%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Kwara State</td>
<td class="gt_row gt_center" headers="stat_0">16 (0.5%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Lagos State</td>
<td class="gt_row gt_center" headers="stat_0">823 (24%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Niger State</td>
<td class="gt_row gt_center" headers="stat_0">3 (&lt;0.1%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Ogun State</td>
<td class="gt_row gt_center" headers="stat_0">1,194 (35%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Ondo State</td>
<td class="gt_row gt_center" headers="stat_0">62 (1.8%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Osun State</td>
<td class="gt_row gt_center" headers="stat_0">152 (4.5%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Oyo State</td>
<td class="gt_row gt_center" headers="stat_0">1,031 (30%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Plateau State</td>
<td class="gt_row gt_center" headers="stat_0">2 (&lt;0.1%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Rivers State</td>
<td class="gt_row gt_center" headers="stat_0">9 (0.3%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Zamfara State</td>
<td class="gt_row gt_center" headers="stat_0">1 (&lt;0.1%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">courseof_study</td>
<td class="gt_row gt_center" headers="stat_0"><br>
</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;AGRICULTURAL AND BIO-RESOURCES ENGINEERING/B.ENG</td>
<td class="gt_row gt_center" headers="stat_0">44 (1.3%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;AGRICULTURE/B.AGRIC.</td>
<td class="gt_row gt_center" headers="stat_0">1,347 (40%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;AQUACULTURE AND FISHERIES MANAGEMENT/B.AQFM</td>
<td class="gt_row gt_center" headers="stat_0">105 (3.1%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;BIOCHEMISTRY/B.SC.</td>
<td class="gt_row gt_center" headers="stat_0">129 (3.8%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;BOTANY/B.SC.</td>
<td class="gt_row gt_center" headers="stat_0">98 (2.9%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;CHEMISTRY/B.Sc.</td>
<td class="gt_row gt_center" headers="stat_0">100 (2.9%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;CIVIL ENGINEERING/B.ENGR.</td>
<td class="gt_row gt_center" headers="stat_0">43 (1.3%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;COMPUTER SCIENCE/B.Sc.</td>
<td class="gt_row gt_center" headers="stat_0">141 (4.1%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;ELECTRICAL AND ELECTRONICS ENGINEERING/B.ENGR.</td>
<td class="gt_row gt_center" headers="stat_0">42 (1.2%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;ENTREPRENEURIAL STUDIES/B.SC.</td>
<td class="gt_row gt_center" headers="stat_0">1 (&lt;0.1%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;ENVIRONMENTAL MANAGEMENT &amp; TOXICOLOGY (ENV. MGT OPTION)/B.EMT</td>
<td class="gt_row gt_center" headers="stat_0">87 (2.6%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;ENVIRONMENTAL MANAGEMENT &amp; TOXICOLOGY (ENV. TOXICOLOGY OPTION)/B.EMT</td>
<td class="gt_row gt_center" headers="stat_0">20 (0.6%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;FOOD SCIENCE AND TECHNOLOGY/B.Sc.</td>
<td class="gt_row gt_center" headers="stat_0">104 (3.1%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;FORESTRY AND WILDLIFE MANAGEMENT (FORESTRY OPTION)/B.FWM</td>
<td class="gt_row gt_center" headers="stat_0">51 (1.5%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;FORESTRY AND WILDLIFE MANAGEMENT (WILDLIFE OPTION)/B.FWM</td>
<td class="gt_row gt_center" headers="stat_0">37 (1.1%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;HOME SCIENCE AND MANAGEMENT(CHILD DEVELOPMENT &amp; FAMILY STUDIES)/B.Sc.</td>
<td class="gt_row gt_center" headers="stat_0">70 (2.1%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;HOME SCIENCE AND MANAGEMENT(CLOTHING &amp; TEXTILE)/B.Sc.</td>
<td class="gt_row gt_center" headers="stat_0">28 (0.8%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;HOME SCIENCE AND MANAGEMENT(EXTENSION &amp; RURAL DEVELOPMENT)/B.Sc.</td>
<td class="gt_row gt_center" headers="stat_0">5 (0.1%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;HOSPITALITY AND TOURISM/B.Sc.</td>
<td class="gt_row gt_center" headers="stat_0">120 (3.5%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;MATHEMATICS/B.Sc.</td>
<td class="gt_row gt_center" headers="stat_0">114 (3.3%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;MECHANICAL ENGINEERING/B.ENGR.</td>
<td class="gt_row gt_center" headers="stat_0">35 (1.0%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;MECHATRONICS ENGINEERING/B.ENGR.</td>
<td class="gt_row gt_center" headers="stat_0">29 (0.9%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;MICROBIOLOGY/B.Sc.</td>
<td class="gt_row gt_center" headers="stat_0">122 (3.6%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;NUTRITION AND DIETETICS/B.Sc.</td>
<td class="gt_row gt_center" headers="stat_0">106 (3.1%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;PHYSICS/B.Sc.</td>
<td class="gt_row gt_center" headers="stat_0">128 (3.8%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;STATISTICS/B.Sc.</td>
<td class="gt_row gt_center" headers="stat_0">125 (3.7%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;VETERINARY MEDICINE/DVM</td>
<td class="gt_row gt_center" headers="stat_0">33 (1.0%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;WATER RESOURCES MANAGEMENT AND AGROMETEOROLOGY (AGROMETEOROLOGY OPTION)/B.WRMA</td>
<td class="gt_row gt_center" headers="stat_0">6 (0.2%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;WATER RESOURCES MANAGEMENT AND AGROMETEOROLOGY (HYDROLOGY OPTION)/B.WRMA</td>
<td class="gt_row gt_center" headers="stat_0">47 (1.4%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;ZOOLOGY/B.SC.</td>
<td class="gt_row gt_center" headers="stat_0">89 (2.6%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">class_of_grade</td>
<td class="gt_row gt_center" headers="stat_0"><br>
</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Third Class</td>
<td class="gt_row gt_center" headers="stat_0">106 (3.1%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Second Class Lower</td>
<td class="gt_row gt_center" headers="stat_0">1,541 (45%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Second Class Upper</td>
<td class="gt_row gt_center" headers="stat_0">1,637 (48%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;First Class</td>
<td class="gt_row gt_center" headers="stat_0">122 (3.6%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">marital_status</td>
<td class="gt_row gt_center" headers="stat_0"><br>
</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;M</td>
<td class="gt_row gt_center" headers="stat_0">2 (&lt;0.1%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;S</td>
<td class="gt_row gt_center" headers="stat_0">3,404 (100%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">gender</td>
<td class="gt_row gt_center" headers="stat_0"><br>
</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;F</td>
<td class="gt_row gt_center" headers="stat_0">1,617 (47%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;M</td>
<td class="gt_row gt_center" headers="stat_0">1,789 (53%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">date_of_birth</td>
<td class="gt_row gt_center" headers="stat_0">2000-09-24 (1999-04-30, 2001-12-09)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">college</td>
<td class="gt_row gt_center" headers="stat_0"><br>
</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;COLAMRUD</td>
<td class="gt_row gt_center" headers="stat_0">361 (11%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;COLANIM</td>
<td class="gt_row gt_center" headers="stat_0">524 (15%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;COLBIOS</td>
<td class="gt_row gt_center" headers="stat_0">438 (13%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;COLENG</td>
<td class="gt_row gt_center" headers="stat_0">193 (5.7%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;COLERM</td>
<td class="gt_row gt_center" headers="stat_0">353 (10%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;COLFHEC</td>
<td class="gt_row gt_center" headers="stat_0">433 (13%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;COLMAS</td>
<td class="gt_row gt_center" headers="stat_0">1 (&lt;0.1%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;COLPHYS</td>
<td class="gt_row gt_center" headers="stat_0">608 (18%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;COLPLANT</td>
<td class="gt_row gt_center" headers="stat_0">462 (14%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;COLVET</td>
<td class="gt_row gt_center" headers="stat_0">33 (1.0%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">deptment_code</td>
<td class="gt_row gt_center" headers="stat_0"><br>
</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;ABE</td>
<td class="gt_row gt_center" headers="stat_0">44 (1.3%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;ABG</td>
<td class="gt_row gt_center" headers="stat_0">85 (2.5%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;AEFM</td>
<td class="gt_row gt_center" headers="stat_0">130 (3.8%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;AERD</td>
<td class="gt_row gt_center" headers="stat_0">110 (3.2%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;AGAD</td>
<td class="gt_row gt_center" headers="stat_0">121 (3.6%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;ANN</td>
<td class="gt_row gt_center" headers="stat_0">120 (3.5%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;ANP</td>
<td class="gt_row gt_center" headers="stat_0">104 (3.1%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;APH</td>
<td class="gt_row gt_center" headers="stat_0">128 (3.8%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;AQFM</td>
<td class="gt_row gt_center" headers="stat_0">105 (3.1%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;BCH</td>
<td class="gt_row gt_center" headers="stat_0">129 (3.8%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;CHM</td>
<td class="gt_row gt_center" headers="stat_0">100 (2.9%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;CPT</td>
<td class="gt_row gt_center" headers="stat_0">85 (2.5%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;CSC</td>
<td class="gt_row gt_center" headers="stat_0">141 (4.1%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;CVE</td>
<td class="gt_row gt_center" headers="stat_0">43 (1.3%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;ELE</td>
<td class="gt_row gt_center" headers="stat_0">42 (1.2%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;EMT</td>
<td class="gt_row gt_center" headers="stat_0">107 (3.1%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;ETS</td>
<td class="gt_row gt_center" headers="stat_0">1 (&lt;0.1%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;FST</td>
<td class="gt_row gt_center" headers="stat_0">104 (3.1%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;FWM</td>
<td class="gt_row gt_center" headers="stat_0">88 (2.6%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;HRT</td>
<td class="gt_row gt_center" headers="stat_0">86 (2.5%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;HSM</td>
<td class="gt_row gt_center" headers="stat_0">103 (3.0%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;HTM</td>
<td class="gt_row gt_center" headers="stat_0">120 (3.5%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;MCB</td>
<td class="gt_row gt_center" headers="stat_0">122 (3.6%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;MCE</td>
<td class="gt_row gt_center" headers="stat_0">35 (1.0%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;MTE</td>
<td class="gt_row gt_center" headers="stat_0">29 (0.9%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;MTS</td>
<td class="gt_row gt_center" headers="stat_0">114 (3.3%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;NUD</td>
<td class="gt_row gt_center" headers="stat_0">106 (3.1%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;PAB</td>
<td class="gt_row gt_center" headers="stat_0">98 (2.9%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;PAZ</td>
<td class="gt_row gt_center" headers="stat_0">89 (2.6%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;PBST</td>
<td class="gt_row gt_center" headers="stat_0">85 (2.5%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;PHS</td>
<td class="gt_row gt_center" headers="stat_0">128 (3.8%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;PPCP</td>
<td class="gt_row gt_center" headers="stat_0">86 (2.5%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;PRM</td>
<td class="gt_row gt_center" headers="stat_0">87 (2.6%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;SSLM</td>
<td class="gt_row gt_center" headers="stat_0">120 (3.5%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;STS</td>
<td class="gt_row gt_center" headers="stat_0">125 (3.7%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;VET</td>
<td class="gt_row gt_center" headers="stat_0">33 (1.0%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;WMA</td>
<td class="gt_row gt_center" headers="stat_0">53 (1.6%)</td>
</tr>
</tbody><tfoot class="gt_footnotes">
<tr class="odd">
<td colspan="2" class="gt_footnote"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span> n (%); Median (Q1, Q3)</td>
</tr>
</tfoot>

</table>

</div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>nysc_list_modified_cleaned <span class="ot">&lt;-</span> nysc_list_modified_cleaned <span class="sc">%&gt;%</span>  <span class="co"># Cleaning the entries of statename for control</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">statename =</span> <span class="fu">case_when</span>(statename <span class="sc">==</span> <span class="st">"Akwa Ibom State"</span> <span class="sc">~</span> <span class="st">"Akwa-Ibom State"</span>,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>                               statename <span class="sc">==</span> <span class="st">"Cross River State"</span> <span class="sc">~</span> <span class="st">"Cross-River State"</span>,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>                               T <span class="sc">~</span> statename))</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>nysc_list_modified_cleaned <span class="ot">&lt;-</span> nysc_list_modified_cleaned <span class="sc">%&gt;%</span> <span class="co"># Splitting statename into state and state1 and dropping the latter</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(statename, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"state"</span>, <span class="st">"state1"</span>), <span class="at">sep =</span> <span class="st">" "</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>state1)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>nysc_list_modified_cleaned <span class="ot">&lt;-</span> nysc_list_modified_cleaned <span class="sc">%&gt;%</span>  <span class="co"># Creating the region column</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">region =</span> <span class="fu">case_when</span>(state <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Kaduna"</span>, <span class="st">"Kogi"</span>, <span class="st">"Niger"</span>, <span class="st">"Plateau"</span>, <span class="st">"Zamfara"</span>, <span class="st">"FCT"</span>) <span class="sc">~</span> <span class="st">"Northern"</span>,</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>                             state <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Abia"</span>, <span class="st">"Anambra"</span>, <span class="st">"Ebonyi"</span>, <span class="st">"Enugu"</span>, <span class="st">"Imo"</span>) <span class="sc">~</span> <span class="st">"Eastern"</span>,</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>                             state <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Akwa-Ibom"</span>, <span class="st">"Cross-River"</span>, <span class="st">"Delta"</span>, <span class="st">"Edo"</span>,<span class="st">"Benue"</span>, <span class="st">"Rivers"</span>) <span class="sc">~</span> <span class="st">"Southern"</span>,</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>                             state <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Ekiti"</span>, <span class="st">"Kwara"</span>, <span class="st">"Lagos"</span>, <span class="st">"Ogun"</span>, <span class="st">"Ondo"</span>, <span class="st">"Osun"</span>, <span class="st">"Oyo"</span>) <span class="sc">~</span> <span class="st">"Western"</span>))</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>nysc_list_modified_cleaned <span class="ot">&lt;-</span> nysc_list_modified_cleaned <span class="sc">%&gt;%</span> <span class="co"># Creating the age column</span></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">age =</span> <span class="fu">round</span>(date_of_birth <span class="sc">%--%</span> <span class="fu">dmy</span>(<span class="st">"02-08-2024"</span>)<span class="sc">/</span><span class="fu">years</span>()))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
</section>
<section id="data-analysis-and-visualization" class="level2">
<h2 class="anchored" data-anchor-id="data-analysis-and-visualization">Data Analysis and Visualization</h2>
<section id="gender-as-a-predictor-of-academic-achievement" class="level3">
<h3 class="anchored" data-anchor-id="gender-as-a-predictor-of-academic-achievement">Gender as a Predictor of Academic Achievement</h3>
<ul>
<li>Is gender associated with academic achievement?</li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>nysc_list_modified_cleaned <span class="sc">%&gt;%</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> class_of_grade)) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">fill =</span> gender)) <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Class of Grade"</span>,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Proportion of Gender within Each Class of Grade"</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Source: FUNAAB 2023/24 NYSC List"</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Gender"</span>)<span class="sc">+</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">face =</span> <span class="st">"bold"</span>,</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">size =</span> <span class="dv">18</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The bar chart above provides a visual representation of the distribution of gender across academic performance categories. It offers an initial impression of how male and female graduates are spread across the different classifications of academic achievement (such as First Class, Second Class Upper, etc.). While the chart reveals some observable patterns — such as possible concentration or variation in specific degree classes for each gender — it does not offer conclusive evidence of a statistically significant relationship between gender and academic performance.</p>
<p>Given that both variables involved are categorical in nature (gender and class of degree), visual inspection alone is insufficient to determine whether an association truly exists between them or if any observed differences are simply due to random variation. Therefore, to formally assess whether a statistically significant relationship exists between gender and academic performance, it is necessary to conduct a Chi-square test of independence. This test will help determine whether the variables are associated or independent of one another.</p>
<section id="chi-square-test-of-independence" class="level4">
<h4 class="anchored" data-anchor-id="chi-square-test-of-independence">Chi-Square Test of Independence</h4>
<p>H<sub>o</sub>: There is no association between gender and academic achievement.</p>
<p>H<sub>1</sub>: There is association between gender and academic achievement.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>nysc_list_modified_cleaned <span class="sc">%&gt;%</span> <span class="co"># Parsing gender and class of grade into a table</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(gender,class_of_grade) <span class="sc">%&gt;%</span> </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      class_of_grade
gender Third Class Second Class Lower Second Class Upper First Class
     F          23                598                931          65
     M          83                943                706          57</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>nysc_list_modified_cleaned <span class="sc">%&gt;%</span> <span class="co"># Finding the chi-square test of independence</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(gender,class_of_grade) <span class="sc">%&gt;%</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>() <span class="sc">%&gt;%</span>  </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">chisq.test</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  .
X-squared = 134.31, df = 3, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>Decision rule:</strong> If p-value is less than 0.05, we reject null hypothesis, otherwise, we fail to reject null hypothesis.</p>
<p><strong>Conclusion:</strong> Since the p-value is less than 0.05, there is enough evidence to conclude that there is association between gender and academic achievement. Hence, we conclude that there is association between gender and academic achievement.</p>
</section>
</section>
<section id="college-as-a-predictor-of-academic-achievement" class="level3">
<h3 class="anchored" data-anchor-id="college-as-a-predictor-of-academic-achievement">College as a Predictor of Academic Achievement</h3>
<ul>
<li>Is college associated with academic achievement?</li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>nysc_list_modified_cleaned <span class="sc">%&gt;%</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(college <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"COLANIM"</span>, <span class="st">"COLAMRUD"</span>,<span class="st">"COLENG"</span>, <span class="st">"COLBIOS"</span>, <span class="st">"COLFHEC"</span>, <span class="st">"COLERM"</span>, <span class="st">"COLPLANT"</span>, <span class="st">"COLVET"</span>, <span class="st">"COLPHYS"</span>)) <span class="sc">%&gt;%</span> <span class="co"># COLMAS was dropped because it produced just one graduate which could consequently flaw our analysis</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span>class_of_grade,<span class="at">fill =</span>  college)) <span class="sc">+</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Class of Grade"</span>,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"College"</span>,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Proportion of college Within Each Class of Grade"</span>) <span class="sc">+</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>,</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">face =</span> <span class="st">"bold"</span>,</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">size =</span> <span class="dv">18</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Following the earlier bar chart on gender and academic performance, which offered insight into how degree classifications are distributed across male and female graduates, the current bar chart extends this exploration by examining the distribution of academic performance across different colleges. This comparison allows for a broader understanding of how academic outcomes vary not only by gender but also by institutional affiliation.</p>
<p>As shown above, the chart provides a visual summary of how graduates from various colleges are represented within each degree classification (for example, First Class, Second Class Upper, and so on). While certain patterns may be visually apparent, such as possible concentrations of specific degree classes within some colleges, these observations are not enough to determine whether a meaningful relationship exists between college and academic performance.</p>
<p>Because both variables, college and class of degree, are categorical, visual inspection alone is not sufficient. Any apparent differences might be due to random variation. To formally assess whether a statistically significant relationship exists, a Chi square test of independence is necessary. This will determine whether college affiliation is associated with academic performance or whether the observed differences occurred by chance.</p>
<section id="chi-square-test-of-independence-1" class="level4">
<h4 class="anchored" data-anchor-id="chi-square-test-of-independence-1">Chi-Square Test of independence</h4>
<p>H<sub>o</sub>: There is no association between gender and academic achievement.</p>
<p>H<sub>1</sub>: There is association between gender and academic achievement.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>tab <span class="ot">&lt;-</span> nysc_list_modified_cleaned <span class="sc">%&gt;%</span> <span class="co">#Parsing college and class of grade into a table</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(college <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"COLANIM"</span>, <span class="st">"COLAMRUD"</span>,<span class="st">"COLENG"</span>, <span class="st">"COLBIOS"</span>, <span class="st">"COLFHEC"</span>, <span class="st">"COLERM"</span>, <span class="st">"COLPLANT"</span>, <span class="st">"COLVET"</span>, <span class="st">"COLPHYS"</span>)) <span class="sc">%&gt;%</span> <span class="co"># filtering COLMAS out since just one graduate was produced by this college</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(college, class_of_grade) <span class="sc">%&gt;%</span> </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">droplevels</span>() <span class="co"># This drops the filtered COLMAS entry</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>tab <span class="sc">%&gt;%</span> </span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(college <span class="sc">==</span> <span class="st">"COLMAS"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 2
# ℹ 2 variables: college &lt;fct&gt;, class_of_grade &lt;ord&gt;</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>cross_tab <span class="ot">&lt;-</span> <span class="fu">table</span>(tab)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>cross_tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>          class_of_grade
college    Third Class Second Class Lower Second Class Upper First Class
  COLAMRUD           3                144                194          20
  COLANIM            9                238                249          28
  COLBIOS           16                170                236          16
  COLENG             3                 64                107          19
  COLERM            16                168                159          10
  COLFHEC            5                123                293          12
  COLPHYS           44                333                225           6
  COLPLANT           9                290                154           9
  COLVET             0                 11                 20           2</code></pre>
</div>
</div>
<p>In this phase of the analysis, the objective is to determine whether there is a significant association between college affiliation and class of degree attained among the graduates under study. The Chi-square test of independence is a widely used statistical method for evaluating such relationships between categorical variables. However, one of its key assumptions is that the expected frequency in each cell of the contingency table should be at least 5.</p>
<p>While the dataset contains a large overall number of observations, certain combinations of college and class of degree — particularly those representing less common degree classifications within specific colleges — have small observed and expected counts. This violates the minimum expected frequency requirement, meaning that the standard Chi-square test’s p-value may be unreliable.</p>
<p>To address this issue, the Monte Carlo simulation version of the Chi-square test was employed. This method involves generating a large number of random contingency tables under the assumption of independence, with the marginal totals fixed. For each simulated table, the Chi-square statistic is calculated, and the p-value is estimated empirically as the proportion of simulated statistics equal to or greater than the observed statistic.</p>
<p>By using this approach, the analysis accounts for the uneven distribution of observations across categories, ensuring that the statistical inference regarding the relationship between college affiliation and class of degree is both valid and robust, even in the presence of small expected counts in some cells.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>cross_tab<span class="sc">%&gt;%</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">chisq.test</span>(<span class="at">simulate.p.value =</span> T, <span class="at">B =</span> <span class="dv">3400</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with simulated p-value (based on 3400
    replicates)

data:  .
X-squared = 266.99, df = NA, p-value = 0.000294</code></pre>
</div>
</div>
<p><strong>Decision rule:</strong> If p-value is less than 0.05, we reject null hypothesis, otherwise, we fail to reject null hypothesis.</p>
<p><strong>Conclusion:</strong> Since the p-value is less than 0.05, there is enough evidence to conclude that there is association between college and academic achievement. Hence, we conclude that there is association between college and academic achievement.</p>
</section>
<section id="post-hoc-test" class="level4">
<h4 class="anchored" data-anchor-id="post-hoc-test">Post-Hoc Test</h4>
<p>The Monte Carlo Chi-square test of independence revealed a statistically significant association between college affiliation and class of degree attained. While this finding establishes that a relationship exists, the Chi-square test does not indicate which specific combinations of categories contribute most to the association. To gain deeper insight, a post hoc analysis was conducted.</p>
<p>Post hoc testing in this context serves to identify the exact College–Class of Degree pairs that deviate significantly from the expected counts under the null hypothesis of independence. This was achieved by examining the standardized residuals from the Chi-square test. Standardized residuals represent the difference between the observed and expected frequencies in each cell of the contingency table, expressed in standard deviation units. Large positive residuals indicate that a particular combination occurred more frequently than expected, while large negative residuals indicate it occurred less frequently than expected.</p>
<p>To control for the increased risk of Type I errors arising from multiple comparisons, the p-values corresponding to the residuals were adjusted using the Bonferroni correction method. This adjustment ensures that the identification of significant cells remains statistically rigorous.</p>
<p>Through this post hoc analysis, the study not only confirms the presence of a relationship between college affiliation and class of degree but also pinpoints the specific areas where the patterns differ, thereby providing more actionable and interpretable findings.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>rcompanion<span class="sc">::</span><span class="fu">pairwiseNominalIndependence</span>(cross_tab,</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>                            <span class="at">fisher =</span> T,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">gtest =</span> F,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>                            <span class="at">chisq =</span> T,</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>                            <span class="at">cramer =</span> T,</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>                            <span class="at">simulate.p.value =</span> T, </span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>                            <span class="at">B =</span> <span class="dv">3400</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>                           )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            Comparison p.Fisher p.adj.Fisher  p.Chisq p.adj.Chisq Cramer.V
1   COLAMRUD : COLANIM 0.231000     0.268000 0.225000    0.261000   0.0707
2   COLAMRUD : COLBIOS 0.033800     0.045100 0.043200    0.057600   0.1020
3    COLAMRUD : COLENG 0.133000     0.160000 0.128000    0.154000   0.0996
4    COLAMRUD : COLERM 0.000294     0.000706 0.000588    0.001180   0.1560
5   COLAMRUD : COLFHEC 0.000588     0.001180 0.000882    0.001670   0.1500
6   COLAMRUD : COLPHYS 0.000294     0.000706 0.000294    0.000662   0.2520
7  COLAMRUD : COLPLANT 0.000294     0.000706 0.000294    0.000662   0.2450
8    COLAMRUD : COLVET 0.767000     0.789000 0.819000    0.839000   0.0473
9    COLANIM : COLBIOS 0.029400     0.040700 0.025000    0.034600   0.0983
10    COLANIM : COLENG 0.007640     0.012000 0.008530    0.013400   0.1250
11    COLANIM : COLERM 0.022900     0.033000 0.023800    0.034300   0.1040
12   COLANIM : COLFHEC 0.000294     0.000706 0.000294    0.000662   0.2030
13   COLANIM : COLPHYS 0.000294     0.000706 0.000294    0.000662   0.2070
14  COLANIM : COLPLANT 0.000294     0.000706 0.000294    0.000662   0.1840
15    COLANIM : COLVET 0.468000     0.527000 0.402000    0.452000   0.0698
16    COLBIOS : COLENG 0.012100     0.018200 0.006760    0.011100   0.1400
17    COLBIOS : COLERM 0.062600     0.080500 0.059700    0.076800   0.0964
18   COLBIOS : COLFHEC 0.000588     0.001180 0.000294    0.000662   0.1510
19   COLBIOS : COLPHYS 0.000294     0.000706 0.000294    0.000662   0.2060
20  COLBIOS : COLPLANT 0.000294     0.000706 0.000294    0.000662   0.2400
21    COLBIOS : COLVET 0.554000     0.587000 0.558000    0.598000   0.0678
22     COLENG : COLERM 0.000294     0.000706 0.000294    0.000662   0.2080
23    COLENG : COLFHEC 0.001180     0.002240 0.000588    0.001180   0.1690
24    COLENG : COLPHYS 0.000294     0.000706 0.000294    0.000662   0.2970
25   COLENG : COLPLANT 0.000294     0.000706 0.000294    0.000662   0.2990
26     COLENG : COLVET 0.926000     0.926000 0.839000    0.839000   0.0692
27    COLERM : COLFHEC 0.000294     0.000706 0.000294    0.000662   0.2390
28    COLERM : COLPHYS 0.007640     0.012000 0.005290    0.009070   0.1160
29   COLERM : COLPLANT 0.000294     0.000706 0.000294    0.000662   0.1580
30     COLERM : COLVET 0.126000     0.156000 0.123000    0.153000   0.1180
31   COLFHEC : COLPHYS 0.000294     0.000706 0.000294    0.000662   0.3290
32  COLFHEC : COLPLANT 0.000294     0.000706 0.000294    0.000662   0.3530
33    COLFHEC : COLVET 0.498000     0.543000 0.565000    0.598000   0.0650
34  COLPHYS : COLPLANT 0.000588     0.001180 0.000294    0.000662   0.1380
35    COLPHYS : COLVET 0.002060     0.003710 0.004410    0.007940   0.1580
36   COLPLANT : COLVET 0.003230     0.005540 0.009110    0.013700   0.1680</code></pre>
</div>
</div>
<p>Post hoc pairwise comparisons using the Chi-square test with Bonferroni adjustment revealed several significant differences in class-of-degree distribution between colleges. Notably, the difference between COLFHEC and COLPLANT was statistically significant (adjusted p = 0.00076) with a Cramér’s V of 0.353, indicating a medium association. Similarly, COLENG vs.&nbsp;COLPHYS (adjusted p = 0.00076, Cramér’s V = 0.297) and COLFHEC vs.&nbsp;COLPHYS (adjusted p = 0.00076, Cramér’s V = 0.329) showed moderate associations. Other significant comparisons, such as COLPHYS vs.&nbsp;COLPLANT (adjusted p = 0.00125, Cramér’s V = 0.138), had smaller effect sizes, suggesting weaker practical differences despite statistical significance.</p>
</section>
</section>
<section id="combined-effect-of-age-gender-college-affiliation-on-the-class-of-degree-attained" class="level3">
<h3 class="anchored" data-anchor-id="combined-effect-of-age-gender-college-affiliation-on-the-class-of-degree-attained">Combined Effect of Age, Gender, College Affiliation on the Class of Degree Attained</h3>
<p>The combined effect of age, gender and college affiliation on the class of degree attained can be examined within the framework of an ordinal logistic regression model, since the class of degree is an ordered categorical outcome. Age may account for variations in academic maturity, while gender could reflect potential disparities in academic engagement or performance. College affiliation captures institutional differences in academic standards, available resources, and programme demands. Modelling these predictors jointly allows for the assessment of both main effects and interaction terms, providing insight into whether the influence of one variable depends on the level of another. This approach ensures a comprehensive statistical evaluation of the multifactorial determinants of academic achievement.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>model_orl <span class="ot">&lt;-</span> <span class="fu">polr</span>(class_of_grade <span class="sc">~</span> age <span class="sc">+</span> college <span class="sc">+</span> gender, <span class="at">data =</span> nysc_list_modified_cleaned, <span class="at">Hess =</span> T)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_orl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
polr(formula = class_of_grade ~ age + college + gender, data = nysc_list_modified_cleaned, 
    Hess = T)

Coefficients:
                    Value Std. Error    t value
age              -0.02427  1.663e-02 -1.459e+00
collegeCOLANIM   -0.28224  1.357e-01 -2.080e+00
collegeCOLBIOS   -0.32851  1.430e-01 -2.297e+00
collegeCOLENG     0.52867  1.837e-01  2.878e+00
collegeCOLERM    -0.61081  1.489e-01 -4.102e+00
collegeCOLFHEC    0.03021  1.453e-01  2.079e-01
collegeCOLMAS   -11.58338  3.476e-06 -3.332e+06
collegeCOLPHYS   -0.95280  1.351e-01 -7.055e+00
collegeCOLPLANT  -0.99820  1.398e-01 -7.142e+00
collegeCOLVET     0.27960  3.674e-01  7.610e-01
genderM          -0.69664  7.407e-02 -9.405e+00

Intercepts:
                                      Value         Std. Error    t value      
Third Class|Second Class Lower              -4.9785        0.4337      -11.4800
Second Class Lower|Second Class Upper       -1.4364        0.4201       -3.4192
Second Class Upper|First Class               2.0810        0.4263        4.8813

Residual Deviance: 6087.421 
AIC: 6115.421 </code></pre>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/ayo-ayorinde\.github\.io");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2025 Ayomide Ayorinde • Powered by Quarto &amp; GitHub Pages</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>