{
  "hash": "864bf0bc48a60834186c2dc9266da628",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"A Cross-Sectional Study of the Effect of Age, College, and Sex on Academic Performance among FUNAAB Graduates Mobilized for NYSC in 2024.\"\nauthor: \"Ayorinde Ayomide David\"\ndate: \"2025-08-12\"\ncategories: [code, analysis, r]\nimage: BGS.jpg\n\nformat:\n  html:\n    code-fold: true\n    code-summary: \"Code\"\n    toc: true\n    toc-depth: 4\n    toc-location: right\n    highlight-style: github  # syntax highlight for code blocks\n    code-copy: true\n    code-overflow: wrap\n    css: styles.css  \n\n---\n\n---\ntitle: \"A Cross-Sectional Study of the Effect of Age, College and Sex on Academic\n  Performance among FUNAAB Graduates Mobilized for NYSC in 2024\"\nauthor: \"Ayorinde Ayomide David\"\ndate: \"2025-08-11\"\noutput: html_document\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n\n## Introduction\n\nAcademic performance remains a central concern for educators, policymakers, and researchers, especially in higher education institutions where various individual and institutional factors may shape students' academic outcomes. While curriculum content and instructional methods often receive primary attention, growing evidence suggests that demographic characteristics such as age, gender, and academic discipline may significantly influence students’ academic achievements.\n\nAge has been associated with varying levels of academic maturity, motivation, and learning capacity. Younger students may possess cognitive flexibility but lack the life experience that older students bring to their studies. Similarly, gender disparities in academic performance, often shaped by socio-cultural expectations and opportunities, continue to attract scholarly interest. In Nigeria and beyond, gender-based performance gaps have been observed across academic disciplines, with conflicting findings on whether male or female students outperform their counterparts.\n\nAdditionally, the academic department or field of study introduces another layer of complexity. Differences in academic rigor, grading policies, and student support structures across departments may contribute to observable disparities in academic outcomes. However, using department as a predictor can be statistically problematic due to sample size imbalances and high variability. As such, grouping departments into broader academic units such as colleges offers a more stable and interpretable approach to understanding institutional influences on performance.\n\nThis study aims to examine the influence of age, gender, and college affiliation on the academic performance of graduates from the Federal University of Agriculture, Abeokuta (FUNAAB), using data from the 2023/2024 NYSC mobilization list. Academic performance is operationalized using the class of degree attained, which serves as a reliable proxy in the absence of raw CGPA. By focusing on a single graduating cohort, the study offers a cross-sectional snapshot of demographic and institutional patterns that may underlie academic success. The findings will provide insights into potential equity issues and inform academic support strategies within the university setting.\n\n## Objective of the Study\n\nThe primary objective of this study is to examine the effect of age, gender, college affiliation, and region of origin on the academic performance of graduates from the Federal University of Agriculture, Abeokuta, using the 2023/2024 NYSC mobilization list.\n\nSpecifically, the study seeks to:\n\n-   Assess the relationship between gender and academic performance among the graduates.\n\n-   Evaluate the extent to which college affiliation (as a proxy for department) affects academic outcomes.\n\n-   Explore the combined effect of age, gender, college affiliation, and region on the class of degree attained.\n\n## Data Description\n\nThis dataset used in this study was obtained from the 2023/24 National Youth Service Corps (NYSC) mobilization list of the Federal University of Agriculture, Abeokuta (FUNAAB). This dataset comprises information on 3406 graduates who were successfully mobilized for national service.\n\nThe dataset includes demographic, academic, and institutional variables relevant to the analysis of academic performance. Each row in the dataset represents an individual graduate, and the variables collected include:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngt(data.frame(Variable_Name = c(\"matriculation_no\", \"state\", \"courseof_study\", \"class_of_grade\", \"marital_status\",\"gender\", \"date_of_birth\", \"college\", \"department_code\", \"age\", \"region\"), Description = c(\"A unique identifier for each student\", \"The Nigeria state attributed to the graduate\", \"The degree programme pursued by the graduate\",\"The final class of degree awarded to the student\", \"The marital status of the graduate (Married or Single)\",\"The sex of the graduate (Male or Female)\",\"The graduate date of birth\", \"The academic unit or faculty under which the student graduated\", \"Abbreviated code representing the graduate's department\", \"Age of graduate\", \"The Nigeria region attributed to the graduate\")))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"lyrjgjkcvd\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#lyrjgjkcvd table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#lyrjgjkcvd thead, #lyrjgjkcvd tbody, #lyrjgjkcvd tfoot, #lyrjgjkcvd tr, #lyrjgjkcvd td, #lyrjgjkcvd th {\n  border-style: none;\n}\n\n#lyrjgjkcvd p {\n  margin: 0;\n  padding: 0;\n}\n\n#lyrjgjkcvd .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#lyrjgjkcvd .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#lyrjgjkcvd .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#lyrjgjkcvd .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#lyrjgjkcvd .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lyrjgjkcvd .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lyrjgjkcvd .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lyrjgjkcvd .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#lyrjgjkcvd .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#lyrjgjkcvd .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#lyrjgjkcvd .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#lyrjgjkcvd .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#lyrjgjkcvd .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#lyrjgjkcvd .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#lyrjgjkcvd .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#lyrjgjkcvd .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#lyrjgjkcvd .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#lyrjgjkcvd .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#lyrjgjkcvd .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lyrjgjkcvd .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#lyrjgjkcvd .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#lyrjgjkcvd .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#lyrjgjkcvd .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lyrjgjkcvd .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#lyrjgjkcvd .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#lyrjgjkcvd .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lyrjgjkcvd .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lyrjgjkcvd .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#lyrjgjkcvd .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lyrjgjkcvd .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#lyrjgjkcvd .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lyrjgjkcvd .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lyrjgjkcvd .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lyrjgjkcvd .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lyrjgjkcvd .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lyrjgjkcvd .gt_left {\n  text-align: left;\n}\n\n#lyrjgjkcvd .gt_center {\n  text-align: center;\n}\n\n#lyrjgjkcvd .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#lyrjgjkcvd .gt_font_normal {\n  font-weight: normal;\n}\n\n#lyrjgjkcvd .gt_font_bold {\n  font-weight: bold;\n}\n\n#lyrjgjkcvd .gt_font_italic {\n  font-style: italic;\n}\n\n#lyrjgjkcvd .gt_super {\n  font-size: 65%;\n}\n\n#lyrjgjkcvd .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#lyrjgjkcvd .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#lyrjgjkcvd .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#lyrjgjkcvd .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#lyrjgjkcvd .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#lyrjgjkcvd .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#lyrjgjkcvd .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#lyrjgjkcvd .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#lyrjgjkcvd div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Variable_Name\">Variable_Name</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Description\">Description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Variable_Name\" class=\"gt_row gt_left\">matriculation_no</td>\n<td headers=\"Description\" class=\"gt_row gt_left\">A unique identifier for each student</td></tr>\n    <tr><td headers=\"Variable_Name\" class=\"gt_row gt_left\">state</td>\n<td headers=\"Description\" class=\"gt_row gt_left\">The Nigeria state attributed to the graduate</td></tr>\n    <tr><td headers=\"Variable_Name\" class=\"gt_row gt_left\">courseof_study</td>\n<td headers=\"Description\" class=\"gt_row gt_left\">The degree programme pursued by the graduate</td></tr>\n    <tr><td headers=\"Variable_Name\" class=\"gt_row gt_left\">class_of_grade</td>\n<td headers=\"Description\" class=\"gt_row gt_left\">The final class of degree awarded to the student</td></tr>\n    <tr><td headers=\"Variable_Name\" class=\"gt_row gt_left\">marital_status</td>\n<td headers=\"Description\" class=\"gt_row gt_left\">The marital status of the graduate (Married or Single)</td></tr>\n    <tr><td headers=\"Variable_Name\" class=\"gt_row gt_left\">gender</td>\n<td headers=\"Description\" class=\"gt_row gt_left\">The sex of the graduate (Male or Female)</td></tr>\n    <tr><td headers=\"Variable_Name\" class=\"gt_row gt_left\">date_of_birth</td>\n<td headers=\"Description\" class=\"gt_row gt_left\">The graduate date of birth</td></tr>\n    <tr><td headers=\"Variable_Name\" class=\"gt_row gt_left\">college</td>\n<td headers=\"Description\" class=\"gt_row gt_left\">The academic unit or faculty under which the student graduated</td></tr>\n    <tr><td headers=\"Variable_Name\" class=\"gt_row gt_left\">department_code</td>\n<td headers=\"Description\" class=\"gt_row gt_left\">Abbreviated code representing the graduate's department</td></tr>\n    <tr><td headers=\"Variable_Name\" class=\"gt_row gt_left\">age</td>\n<td headers=\"Description\" class=\"gt_row gt_left\">Age of graduate</td></tr>\n    <tr><td headers=\"Variable_Name\" class=\"gt_row gt_left\">region</td>\n<td headers=\"Description\" class=\"gt_row gt_left\">The Nigeria region attributed to the graduate</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n## Data Exploration, Cleaning, Manipulation and Transformation\n\nTo begin the analysis, the necessary R packages were loaded, including tidyverse, gt, here, janitor, lubridate, and visdat, which collectively support data manipulation, visualization, and cleaning. Following this, the NYSC dataset was imported into the R environment. An initial assessment was conducted to determine the dataset's structure, including the number of rows and columns, and to preview the first ten records.\n\nThe properties of each variable were inspected to understand data types and formats. Special attention was given to the Date of Graduation column, which was found to contain a substantial number of missing values. This observation was first noted during the structure inspection and subsequently confirmed using summary statistics and missing value checks.\n\nTo preserve confidentiality and ensure ethical data handling, columns containing sensitive or personally identifiable information such as names, phone numbers,jamb registration number and matric numbers were excluded from the working dataset. A new CSV file was then generated to store this modified version of the dataset.\n\nFinally, data cleaning and transformation were carried out on the refined dataset. This included tasks such as deriving new variables (age and region), and preparing the data for statistical analysis.\n\n### Data Exploration\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#nysc <- read_csv(here(\"Data/NYSC.csv\"))    # Loading the dataset into R\n\n#dim(nysc) # Investigating the dimension of the dataset\n\n#head(nysc, n= 10) # Exploring the first 10 rows of the dataset\n\n#glimpse(nysc)    # Investigating the properties of the dataset\n\n#sum(is.na(nysc$`Date of Graduation`))    # Investigating the number of missing values in the Date of Graduation colunm\n\n#nysc_list <- nysc %>% # Dropping private information columns and the column with no entry\n  #mutate(id = str_sub(JambNumber, -8, -1)) %>% \n  #select(-c(Firstname,Middlename, Surname, MatriculationNo,JambNumber, Phone, `Date of Graduation`)) %>% \n  #select(id, everything()) # This ensures the id column comes first in the dataset\n  \n\n#write_csv(nysc_list,\"nysc_modified.csv\") # Creating a csv file for the modified dataset\n```\n:::\n\n\n\n### Data Cleaning\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnysc_list_modified <- read_csv(here(\"posts/Academic performance/data/nysc_modified.csv\")) # Loading the modified dataset into R\n\nvis_dat(nysc_list_modified) # Visualizing the dataset to investigate it's properties\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n\n```{.r .cell-code}\nnysc_list_modified_cleaned <- nysc_list_modified %>%    # Cleaning the column name for consistency\n    clean_names()\n\ndup <- nysc_list_modified_cleaned %>%  # Identifying duplicated rows based on matriculation number\n  get_dupes(id)\n\n\nnysc_list_modified_cleaned <- nysc_list_modified_cleaned %>%    # Dropping duplicated rows\n  unique()\n\nnysc_list_modified_cleaned <- nysc_list_modified_cleaned %>%    # Changing the class of some of our categorical variable to allow for efficient data analysis\n  mutate(class_of_grade = factor(class_of_grade,\n                                     levels = c(\"Third Class\",\"Second Class Lower\", \"Second Class Upper\", \"First Class\"), \n                                 ordered = T),\n         gender = factor(gender),\n         college = factor(college))\n\n# nysc_list_modified_cleaned %>% # This was done to have a thorough look at each unique entry of each column of the dataset in order to have the dataset cleaned appropriately. It was commented out to avoid much digression while going through the study.\n  #dplyr::select(-id) %>% \n  #tbl_summary()\n```\n:::\n\n\n\n### Data Manipulation and Transformation\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnysc_list_modified_cleaned <- nysc_list_modified_cleaned %>%  # Cleaning the entries of statename for control\n  mutate(statename = case_when(statename == \"Akwa Ibom State\" ~ \"Akwa-Ibom State\",\n                               statename == \"Cross River State\" ~ \"Cross-River State\",\n                               T ~ statename))\n\nnysc_list_modified_cleaned <- nysc_list_modified_cleaned %>% # Splitting statename into state and state1 and dropping the latter\n  separate(statename, into = c(\"state\", \"state1\"), sep = \" \") %>% \n  dplyr::select(-state1)\n  \n\nnysc_list_modified_cleaned <- nysc_list_modified_cleaned %>%  # Creating the region column\n  mutate(region = case_when(state %in% c(\"Kaduna\", \"Kogi\", \"Niger\", \"Plateau\", \"Zamfara\", \"FCT\") ~ \"Northern\",\n                             state %in% c(\"Abia\", \"Anambra\", \"Ebonyi\", \"Enugu\", \"Imo\") ~ \"Eastern\",\n                             state %in% c(\"Akwa-Ibom\", \"Cross-River\", \"Delta\", \"Edo\",\"Benue\", \"Rivers\") ~ \"Southern\",\n                             state %in% c(\"Ekiti\", \"Kwara\", \"Lagos\", \"Ogun\", \"Ondo\", \"Osun\", \"Oyo\") ~ \"Western\"))\n  \n\nnysc_list_modified_cleaned <- nysc_list_modified_cleaned %>% # Creating the age column\n  mutate(age = round(date_of_birth %--% dmy(\"02-08-2024\")/years()))\n```\n:::\n\n\n\n## Data Analysis and Visualization\n\n### Gender as a Predictor of Academic Achievement\n\n-   Is gender associated with academic achievement?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnysc_list_modified_cleaned %>% \n  ggplot(mapping = aes(x = class_of_grade)) +\n  geom_bar(mapping = aes(fill = gender)) +\n  labs(x = \"Class of Grade\",\n       title = \"Proportion of Gender within Each Class of Grade\",\n       caption = \"Source: FUNAAB 2023/24 NYSC List\",\n       fill = \"Gender\")+\n  theme_minimal() +\n  theme(plot.title = element_text(hjust = 0.5,\n                                  face = \"bold\",\n                                  size = 18))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\nThe bar chart above provides a visual representation of the distribution of gender across academic performance categories. It offers an initial impression of how male and female graduates are spread across the different classifications of academic achievement (such as First Class, Second Class Upper, etc.). While the chart reveals some observable patterns such as possible concentration or variation in specific degree classes for each gender, it does not offer conclusive evidence of a statistically significant relationship between gender and academic performance.\n\nGiven that both variables involved are categorical in nature (gender and class of degree), visual inspection alone is insufficient to determine whether an association truly exists between them or if any observed differences are simply due to random variation. Therefore, to formally assess whether a statistically significant relationship exists between gender and academic performance, it is necessary to conduct a Chi-square test of independence. This test will help determine whether the variables are associated or independent of one another.\n\n#### Chi-Square Test of Independence\n\nH~o~: There is no association between gender and academic achievement.\n\nH~1~: There is association between gender and academic achievement.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnysc_list_modified_cleaned %>% # Parsing gender and class of grade into a table\n  dplyr::select(gender,class_of_grade) %>% \n  table()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      class_of_grade\ngender Third Class Second Class Lower Second Class Upper First Class\n     F          23                598                931          65\n     M          83                943                706          57\n```\n\n\n:::\n\n```{.r .cell-code}\nnysc_list_modified_cleaned %>% # Finding the chi-square test of independence\n  dplyr::select(gender,class_of_grade) %>% \n  table() %>%  \n  chisq.test()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  .\nX-squared = 134.31, df = 3, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n**Decision rule:** If p-value is less than 0.05, we reject null hypothesis, otherwise, we fail to reject null hypothesis.\n\n**Conclusion:** Since the p-value is less than 0.05, there is enough evidence to conclude that there is association between gender and academic achievement. Hence, we conclude that there is a difference in gender proportion across the class of degree groups.\n\n### College as a Predictor of Academic Achievement\n\n-   Is college associated with academic achievement?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnysc_list_modified_cleaned %>% \n  filter(college %in% c(\"COLANIM\", \"COLAMRUD\",\"COLENG\", \"COLBIOS\", \"COLFHEC\", \"COLERM\", \"COLPLANT\", \"COLVET\", \"COLPHYS\")) %>% # \n  droplevels() %>% # COLMAS was filtered and dropped because she produced just one graduate\n  ggplot(mapping = aes(x =class_of_grade,fill =  college)) +\n  geom_bar(position = \"dodge\") +\n  labs(x = \"Class of Grade\",\n       fill = \"College\",\n       title = \"Proportion of college Within Each Class of Grade\") +\n  theme_minimal() +\n  theme(plot.title = element_text(hjust = 0.5,\n                                  face = \"bold\",\n                                  size = 18))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\nFollowing the earlier bar chart on gender and academic performance, which offered insight into how degree classifications are distributed across male and female graduates, the current bar chart extends this exploration by examining the distribution of academic performance across different colleges. This comparison allows for a broader understanding of how academic outcomes vary not only by gender but also by institutional affiliation.\n\nAs shown above, the chart provides a visual summary of how graduates from various colleges are represented within each degree classification (for example, First Class, Second Class Upper, and so on). While certain patterns may be visually apparent, such as possible concentrations of specific degree classes within some colleges, these observations are not enough to determine whether a meaningful relationship exists between college and academic performance.\n\nBecause both variables, college and class of degree, are categorical, visual inspection alone is not sufficient. Any apparent differences might be due to random variation. To formally assess whether a statistically significant relationship exists, a Chi square test of independence is necessary. This will determine whether college affiliation is associated with academic performance or whether the observed differences occurred by chance.\n\n#### Chi-Square Test of independence\n\n\nH~o~: There is no association between gender and academic achievement.\n\nH~1~: There is association between gender and academic achievement.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab <- nysc_list_modified_cleaned %>% #Parsing college and class of grade into a table\n  filter(college %in% c(\"COLANIM\", \"COLAMRUD\",\"COLENG\", \"COLBIOS\", \"COLFHEC\", \"COLERM\", \"COLPLANT\", \"COLVET\", \"COLPHYS\")) %>% # filtering COLMAS out since just one graduate was produced by this college\n  dplyr::select(college, class_of_grade) %>% \n  droplevels() # This drops the filtered COLMAS entry\n\n  \ncross_tab <- table(tab)\ncross_tab\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          class_of_grade\ncollege    Third Class Second Class Lower Second Class Upper First Class\n  COLAMRUD           3                144                194          20\n  COLANIM            9                238                249          28\n  COLBIOS           16                170                236          16\n  COLENG             3                 64                107          19\n  COLERM            16                168                159          10\n  COLFHEC            5                123                293          12\n  COLPHYS           44                333                225           6\n  COLPLANT           9                290                154           9\n  COLVET             0                 11                 20           2\n```\n\n\n:::\n:::\n\n\n\n\nIn this phase of the analysis, the objective is to determine whether there is a significant association between college affiliation and class of degree attained among the graduates under study. While the dataset contains a large overall number of observations, certain combinations of college and class of degree — particularly those representing less common degree classifications within specific colleges — have small observed and expected counts. This violates the minimum expected frequency requirement, meaning that the standard Chi-square test’s p-value may be unreliable.\n\nTo address this issue, the Monte Carlo simulation version of the Chi-square test was employed. This method involves generating a large number of random contingency tables under the assumption of independence, with the marginal totals fixed. For each simulated table, the Chi-square statistic is calculated, and the p-value is estimated empirically as the proportion of simulated statistics equal to or greater than the observed statistic.\n\nBy using this approach, the analysis accounts for the uneven distribution of observations across categories, ensuring that the statistical inference regarding the relationship between college affiliation and class of degree is both valid and robust, even in the presence of small expected counts in some cells.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncross_tab%>% \n  chisq.test(simulate.p.value = T, B = 3400)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with simulated p-value (based on 3400\n\treplicates)\n\ndata:  .\nX-squared = 266.99, df = NA, p-value = 0.000294\n```\n\n\n:::\n:::\n\n\n\n\n**Decision rule:** If p-value is less than 0.05, we reject null hypothesis, otherwise, we fail to reject null hypothesis.\n\n**Conclusion:** Since the p-value is less than 0.05, there is enough evidence to conclude that there is association between college and academic achievement. Hence, we conclude that there is a difference in college proportion across the class of degree groups.\n\n\n#### Post-Hoc Test\n\nThe Monte Carlo Chi-square test of independence revealed a statistically significant association between college affiliation and class of degree attained. While this finding establishes that a relationship exists, the Chi-square test does not indicate which specific combinations of categories contribute most to the association. To gain deeper insight, a post hoc analysis will be conducted.\n\nThrough this post hoc analysis, the study not only confirms the presence of a relationship between college affiliation and class of degree but also pinpoints the specific areas where the patterns differ, thereby providing more actionable and interpretable findings.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(200)\nrcompanion::pairwiseNominalIndependence(cross_tab,\n                            fisher = T,\n                            gtest = F,\n                            chisq = T,\n                            cramer = T,\n                            simulate.p.value = T, \n                            B = 3400\n                           )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Comparison p.Fisher p.adj.Fisher  p.Chisq p.adj.Chisq Cramer.V\n1   COLAMRUD : COLANIM 0.223000     0.259000 0.213000    0.247000   0.0707\n2   COLAMRUD : COLBIOS 0.032000     0.042700 0.046200    0.061600   0.1020\n3    COLAMRUD : COLENG 0.133000     0.165000 0.141000    0.175000   0.0996\n4    COLAMRUD : COLERM 0.000294     0.000623 0.000588    0.001250   0.1560\n5   COLAMRUD : COLFHEC 0.001180     0.002240 0.000294    0.000706   0.1500\n6   COLAMRUD : COLPHYS 0.000294     0.000623 0.000294    0.000706   0.2520\n7  COLAMRUD : COLPLANT 0.000294     0.000623 0.000294    0.000706   0.2450\n8    COLAMRUD : COLVET 0.779000     0.801000 0.805000    0.828000   0.0473\n9    COLANIM : COLBIOS 0.022100     0.031800 0.024100    0.033400   0.0983\n10    COLANIM : COLENG 0.010000     0.015000 0.009410    0.014600   0.1250\n11    COLANIM : COLERM 0.023200     0.032100 0.021500    0.031000   0.1040\n12   COLANIM : COLFHEC 0.000294     0.000623 0.000294    0.000706   0.2030\n13   COLANIM : COLPHYS 0.000294     0.000623 0.000294    0.000706   0.2070\n14  COLANIM : COLPLANT 0.000294     0.000623 0.000294    0.000706   0.1840\n15    COLANIM : COLVET 0.455000     0.512000 0.414000    0.466000   0.0698\n16    COLBIOS : COLENG 0.007350     0.011500 0.006760    0.011600   0.1400\n17    COLBIOS : COLERM 0.063200     0.081300 0.063500    0.081600   0.0964\n18   COLBIOS : COLFHEC 0.000294     0.000623 0.001180    0.002240   0.1510\n19   COLBIOS : COLPHYS 0.000294     0.000623 0.000294    0.000706   0.2060\n20  COLBIOS : COLPLANT 0.000294     0.000623 0.000294    0.000706   0.2400\n21    COLBIOS : COLVET 0.537000     0.569000 0.553000    0.603000   0.0678\n22     COLENG : COLERM 0.000294     0.000623 0.000294    0.000706   0.2080\n23    COLENG : COLFHEC 0.000294     0.000623 0.000882    0.001760   0.1690\n24    COLENG : COLPHYS 0.000294     0.000623 0.000294    0.000706   0.2970\n25   COLENG : COLPLANT 0.000294     0.000623 0.000294    0.000706   0.2990\n26     COLENG : COLVET 0.931000     0.931000 0.833000    0.833000   0.0692\n27    COLERM : COLFHEC 0.000294     0.000623 0.000294    0.000706   0.2390\n28    COLERM : COLPHYS 0.004700     0.007690 0.003530    0.006350   0.1160\n29   COLERM : COLPLANT 0.000294     0.000623 0.000294    0.000706   0.1580\n30     COLERM : COLVET 0.141000     0.169000 0.149000    0.179000   0.1180\n31   COLFHEC : COLPHYS 0.000294     0.000623 0.000294    0.000706   0.3290\n32  COLFHEC : COLPLANT 0.000294     0.000623 0.000294    0.000706   0.3530\n33    COLFHEC : COLVET 0.491000     0.536000 0.575000    0.609000   0.0650\n34  COLPHYS : COLPLANT 0.000588     0.001180 0.000588    0.001250   0.1380\n35    COLPHYS : COLVET 0.002350     0.004030 0.007940    0.013000   0.1580\n36   COLPLANT : COLVET 0.002060     0.003710 0.009700    0.014600   0.1680\n```\n\n\n:::\n:::\n\n\n\n\nPost hoc pairwise comparisons using the Chi-square test with Bonferroni adjustment revealed several significant differences in class-of-degree distribution between colleges. Notably, the difference between COLFHEC and COLPLANT was statistically significant (adjusted p = 0.000706) with a Cramér’s V of 0.353, indicating a medium association. Similarly, COLENG vs. COLPHYS (adjusted p = 0.000706, Cramér’s V = 0.297) and COLFHEC vs. COLPHYS (adjusted p = 0.00076, Cramér’s V = 0.329) showed moderate associations. Other significant comparisons, such as COLPHYS vs. COLPLANT (adjusted p = 0.00125, Cramér’s V = 0.138), had smaller effect sizes, suggesting weaker practical differences despite statistical significance.\n\n\n### Combined Effect of Age, Gender, College Affiliation on the Class of Degree Attained\n\n\nThe combined effect of age, gender and college affiliation on the class of degree attained can be examined within the framework of an ordinal logistic regression model, since the class of degree is an ordered categorical outcome. Age may account for variations in academic maturity, while gender could reflect potential disparities in academic engagement or performance. College affiliation captures institutional differences in academic standards, available resources, and programme demands. Modelling these predictors jointly allows for the assessment of both main effects and interaction terms, providing insight into whether the influence of one variable depends on the level of another. This approach ensures a comprehensive statistical evaluation of the multifactorial determinants of academic achievement.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_orl <- polr(class_of_grade ~ age + college + gender, data = nysc_list_modified_cleaned, Hess = T)\n\nsummary(model_orl)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\npolr(formula = class_of_grade ~ age + college + gender, data = nysc_list_modified_cleaned, \n    Hess = T)\n\nCoefficients:\n                    Value Std. Error    t value\nage              -0.02427  1.663e-02 -1.459e+00\ncollegeCOLANIM   -0.28224  1.357e-01 -2.080e+00\ncollegeCOLBIOS   -0.32851  1.430e-01 -2.297e+00\ncollegeCOLENG     0.52867  1.837e-01  2.878e+00\ncollegeCOLERM    -0.61081  1.489e-01 -4.102e+00\ncollegeCOLFHEC    0.03021  1.453e-01  2.079e-01\ncollegeCOLMAS   -11.58338  3.476e-06 -3.332e+06\ncollegeCOLPHYS   -0.95280  1.351e-01 -7.055e+00\ncollegeCOLPLANT  -0.99820  1.398e-01 -7.142e+00\ncollegeCOLVET     0.27960  3.674e-01  7.610e-01\ngenderM          -0.69664  7.407e-02 -9.405e+00\n\nIntercepts:\n                                      Value         Std. Error    t value      \nThird Class|Second Class Lower              -4.9785        0.4337      -11.4800\nSecond Class Lower|Second Class Upper       -1.4364        0.4201       -3.4192\nSecond Class Upper|First Class               2.0810        0.4263        4.8813\n\nResidual Deviance: 6087.421 \nAIC: 6115.421 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n:::\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}